### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by WeiquanWa** [Zeqiang-Lai/DragGAN#1]
Hello, 
Thank you for sharing. Can you post a requirements.txt file?

**Comment by Zeqiang-Lai** [comment]
We have uploaded one.
The only requirements are
```
gradio
tqdm
torch
```

**Comment by WeiquanWa** [comment]
Is there any specific requirement on a version of each package?

**Comment by Zeqiang-Lai** [comment]
Probably no.

Just for reference.
I use torch1.10, and the latest gradio and tqdm should just work.

**Comment by WeiquanWa** [comment]
cool. thank you. I will try to give some testing.
