### ISSUE TITLE
Which torch is supported? 

### ISSUE THREAD

**Issue by DuckersMcQuack** [Zeqiang-Lai/DragGAN#10]
(DRAGGANTEST) C:\Users\Duckers\Downloads\DragGAN-main>python gradio_app.py
stylegan2-ffhq-config-f.pt not found
Try to download from huggingface:  https://huggingface.co/aaronb/StyleGAN2/resolve/main/stylegan2-ffhq-config-f.pt
stylegan2-ffhq-config-f.pt: 133MB [00:02, 47.1MB/s]
Downloaded to  checkpoints\stylegan2-ffhq-config-f.pt
C:\Users\Duckers\Downloads\DragGAN-main\stylegan2\op\conv2d_gradfix.py:88: UserWarning: conv2d_gradfix not supported on PyTorch 2.0.1. Falling back to torch.nn.functional.conv2d().
  warnings.warn(
  
  As conv2d isn't supported on pytorch 2.0.1. I can generate, but not save.

**Comment by Zeqiang-Lai** [comment]
Hi, from my test, pytorch 2.x works. The problem might be the lack of `imageio-ffmpeg`

It can be installed via
```
pip install imageio-ffmpeg
```

Could you try it and see if the error still exists?

**Comment by marwanmusa** [comment]
As you can see in `conv2d_gradfix.py` it will use backend torch in version 1.7 and 1.8

![image](https://github.com/Zeqiang-Lai/DragGAN/assets/101170033/93576820-01e8-4166-a252-cd1a251e8251)

otherwise it'll use `torch.nn.functional.conv2d()`
