### ISSUE TITLE
Error in Mask

### ISSUE THREAD

**Issue by CHNxindong** [Zeqiang-Lai/DragGAN#112]
感谢您的贡献，我在使用时遇到2个问题，希望得到您的帮助
1. 选择MakTab时，会报Error的错，
![image](https://github.com/OpenGVLab/DragGAN/assets/20262070/121c7d5f-f7c9-47a3-8aea-ea4f15c99f6b)

命令行的报错为：
![image](https://github.com/OpenGVLab/DragGAN/assets/20262070/eb0913de-d36e-47d5-ae5e-69bdf0991361)
就是说state没有sample这个字段，我看了state的定义，确实没有sample字段。请问您有什么建议？

2. 当选择New Image，并且不修改seed时，会报Error的错
![image](https://github.com/OpenGVLab/DragGAN/assets/20262070/7afeb50d-5560-4e44-80ff-44b56d1c0fe0)

![image](https://github.com/OpenGVLab/DragGAN/assets/20262070/6cc88233-2dc0-4abc-960c-9da5e2265c72)

命令行信息为
![image](https://github.com/OpenGVLab/DragGAN/assets/20262070/45621a15-4caa-4408-838e-532c5d8cebc6)

**Comment by hak650** [comment]
Hi kay

**Comment by Zeqiang-Lai** [comment]
新版本修复了旧版本有些模型编辑会很容易失败的问题，但目前还没完全适配好。

你可以尝试安装旧版本，并选择人脸和狮子的模型体验，这两个模型暂时没观察到容易失败的问题并且适配性比较好。
```
pip install draggan==1.1.0
```
