### ISSUE TITLE
gradio_app.py error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Zeqiang-Lai/DragGAN#16]
I tried to run gradio_app.py, but error has occurred.

There are only black points, no red and blue point.
The error image is as follows.

![Screenshot from 2023-05-23 10-29-18](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/a4d253af-9ce9-402a-89b9-33fcc07e05f3)

**Comment by Zeqiang-Lai** [comment]
You need to switch to the setup handle points pannel to click points.
The black mask is used to identify the editable region, which is not ncessary.

<img width="715" alt="image" src="https://github.com/Zeqiang-Lai/DragGAN/assets/26198430/226fcc72-54c0-4924-9716-d296810ce40e">

**Comment by Ishihara-Masabumi** [comment]
Thank you.
