### ISSUE TITLE
The select point doesn't move to the target point.

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Zeqiang-Lai/DragGAN#17]
I set the select point and the target point as the following image.

![image_a9a389c1-504e-4d0c-8b78-4ef8ec7d1aa1](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/bf393b82-f910-4c83-b97c-4c85d339713c)

But the select point doesn't move to the target point as the following movie.

https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/f307db4a-8715-49bf-a8a1-b81c3a09256a

**Comment by Zeqiang-Lai** [comment]
It actually move a little bit. You need to increase max iterations to make the face fully turned.
