### ISSUE TITLE
The nose has been larger and the face has distorted.

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Zeqiang-Lai/DragGAN#19]
I set the max iterations 201 and tried to run it.
The setect point is close to the target point, but the nose has been larger and the face has distorted.

![image_40a805fd-04dc-4e57-8a78-ebc2ce834179](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/fce46ae0-8dbb-4f88-9f15-fb0dc165d2c8)

**Comment by Zeqiang-Lai** [comment]
Well, our implementation is not perfect and could fail in many cases. I will try to tweak the performance. Also pay attention to the official implementation when it is released. Their one might be better.

**Comment by Ishihara-Masabumi** [comment]
Thank you.
I'm looking forward to getting the new release.
