### ISSUE TITLE
I can't select the multiple select points and target points.

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Zeqiang-Lai/DragGAN#20]
I tried to select the multiple select points and target points.
But, I can't select the multiple select points and target points like the below image.
Just only each one point.

![Screenshot from 2023-05-23 11-47-29](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/bc4dc960-9465-4a69-ba6c-b52bc1994914)

**Comment by Ishihara-Masabumi** [comment]
I solved it by myself.

**Comment by Zeqiang-Lai** [comment]
Cool
