### ISSUE TITLE
_get_cuda_arch_flags() error

### ISSUE THREAD

**Issue by hnsigma** [Zeqiang-Lai/DragGAN#21]
Have everything properly installed but get this issue both in the notebook and on local version

line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
    ~~~~~~~~~^^^^
IndexError: list index out of range

**Comment by fuadmefleh** [comment]
The top of the error likely mentions that you have no CUDA runtime installed. 

`$ python gradio_app.py
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'`

**Comment by hnsigma** [comment]
I defo have cuda installed, and tried various versions, I tried using conda also, always the same error. Is there an environment setup I need to do perhaps that didn't happen automatically with the install?

**Comment by Zeqiang-Lai** [comment]
It should run without any special setup. Could you run the following snippet with python interpreter at your env and see if it print True ?
```
import torch
print(torch.cuda.is_available())
```

**Comment by hnsigma** [comment]
I get false, which is very strange, I have installed cuda several times now. Apologies for my errors! could it be an environment variable issue?

**Comment by Zeqiang-Lai** [comment]
It might be, but I could not give a certain answer. Another option is to use our online colab demo where you could obtain a free GPU from google.

**Comment by genecyber** [comment]
online collab demo is throwing the same error.

**Comment by Zeqiang-Lai** [comment]
> online collab demo is throwing the same error.


Did you select a GPU via Runtime/Change runtime type ?

**Comment by d8ahazard** [comment]
Probably need to add "--extra-index-url https://download.pytorch.org/whl/cu118" to the top of the requirements.txt file so that it knows to install torch+cuda, versus just torch. ;)
