### ISSUE TITLE
Lion head didn't move and mouth didn't open.

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Zeqiang-Lai/DragGAN#22]
I tried to move lion head front to side and open the mouth like the example of this repository.
But, lion head didn't move and mouth didn't open, as the following image.
Moreover, the lion face distorted badly.

![Screenshot from 2023-05-23 14-07-30](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/485ef394-4dfa-4da4-9ddb-a7df5aac30a2)

**Comment by Zeqiang-Lai** [comment]
The default GAN model is trained on human face. Maybe switch to model trained on cat could help.
<img width="221" alt="image" src="https://github.com/Zeqiang-Lai/DragGAN/assets/26198430/289789b3-eecf-44e4-b93b-826bcd23770a">
