### ISSUE TITLE
Lion face changed but distorted

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Zeqiang-Lai/DragGAN#24]
This time, I loaded the lion image as below.

![lion](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/2c2ec3d4-ef69-48b3-8bac-2f9e25283d7f)

After changing the face, the face was fully distorted as below.

![image_ea5cda60-32ae-46cd-a387-6564c7be8a90](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/e0fd5581-34b8-4f01-8802-c87c29b7ae25)

**Comment by Zeqiang-Lai** [comment]
Due to the limitation of GAN inversion, it is possible that your custom images are distorted. Besides, it is also possible the manipulations fail due to the limitation of our implementation.
