### ISSUE TITLE
Woman face collapsed after rotation

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Zeqiang-Lai/DragGAN#26]
I run the woman face rotation, but the final face was collapsed as the following image.
Especially, around the left eye is blue, the nose is big.

![Screenshot from 2023-05-23 15-53-37](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/6f2b64be-85b6-4a60-8d7f-42b6ff845732)

**Comment by Zeqiang-Lai** [comment]
Due to the limitation of GAN inversion, it is possible that your custom images are distorted. Besides, it is also possible the manipulations fail due to the limitation of our implementation.
