### ISSUE TITLE
different framework

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Zeqiang-Lai/DragGAN#27]
I saw DragGAN on the twitter as the below image.

![Screenshot from 2023-05-23 16-59-47](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/79434929-c1b9-44f4-83de-1eb0eca91201)
![Screenshot from 2023-05-23 17-04-54](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/ab8f62d3-829d-4fd4-8407-a50cb9f3b751)
![Screenshot from 2023-05-23 17-07-40](https://github.com/Zeqiang-Lai/DragGAN/assets/23301778/19d818f6-d5ad-4913-ae1c-fbffd286ec33)

I think the framework of the twitter is different from this one.
Is that so?

**Comment by Zeqiang-Lai** [comment]
Yes, we use gradio to construct gui, we don't know what the original author uses
