### ISSUE TITLE
无法正常显示图片

### ISSUE THREAD

**Issue by PetentWong** [Zeqiang-Lai/DragGAN#33]
在本地部署时 遇到了gradio app中无法正常显示图片的问题，只显示一张纯色（橘色）图片，使用new image换图也无法解决这个问题，期待您的帮助
<img width="1381" alt="图片" src="https://github.com/Zeqiang-Lai/DragGAN/assets/109642333/80a07d8b-2ad8-47dc-8885-3b4df7fcedad">

**Comment by PetentWong** [comment]
当使用自定义图片时也会出现纯黑色的情况。    注意到上传图片时mse大部分时间为nan
<img width="994" alt="图片" src="https://github.com/Zeqiang-Lai/DragGAN/assets/109642333/f249d6fa-be68-4c95-a82c-15cddebc35db">

**Comment by Zeqiang-Lai** [comment]
请问你有改过代码吗，我这边无法复现你的问题，并且colab上的demo也能正常运行。

如果没有改动过，可能是依赖库或者其他问题。你可以参考这里安装制定版本的依赖库试试

https://github.com/Zeqiang-Lai/DragGAN/issues/11#issuecomment-1556859509

**Comment by PetentWong** [comment]
按照#11试过了 还是同样的问题。我使用的是wsl2的ubuntu2204 ,torch版本是2.0.1,没有改过源码

**Comment by PetentWong** [comment]
解决了 升级了cu117为cu121解决的

**Comment by Zeqiang-Lai** [comment]
可以👍
