### ISSUE TITLE
Cannot use custom image

### ISSUE THREAD

**Issue by ritsukaginn** [Zeqiang-Lai/DragGAN#4]
The tool is nice, but does not work with custom image yet.

1. get error when uploaded image is not in size 1024*1024
2. will automatically change back to the demo image when "drag it" is clicked

**Comment by Zeqiang-Lai** [comment]
Yes, dragging custom image needs GAN inversion to find the latent code, which has not been added yet. I will try to add it later.

**Comment by jmscxnulleins** [comment]
Thank you very much for your work and thanks for the informations!

**Comment by Ainaemaet** [comment]
This is pretty amazing tbh. Thanks for putting up this implementation for us and looking forwards to being able to try with custom image. 
Very excited about a future web-ui extension, this would round-up the toolset quite nicely. 

Keep up the great work!

**Comment by Zeqiang-Lai** [comment]
Custom image has been supported
