### ISSUE TITLE
ERROR: No matching distribution found for draggan

### ISSUE THREAD

**Issue by cwjcw** [Zeqiang-Lai/DragGAN#43]
windows 11, can't install draggan.
error below:
command is : (draggan) C:\Users\Administrator>pip install draggan
ERROR: Could not find a version that satisfies the requirement draggan (from versions: none)
ERROR: No matching distribution found for draggan

**Comment by Zeqiang-Lai** [comment]
Due to unknown reasons, some pypi source did not sync draggan, please try
```
pip install draggan -i https://pypi.org/simple/
```

**Comment by cwjcw** [comment]
Worked!  Thanks for your help!
