### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by cwjcw** [Zeqiang-Lai/DragGAN#44]
I can open the web and set blue and red point. But after I click "drag it", it shows "error", in Anaconda prompt, the error message is: 
"torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 4.00 GiB total capacity; 3.07 GiB already allocated; 0 bytes free; 3.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

![企业微信截图_16850877962092](https://github.com/Zeqiang-Lai/DragGAN/assets/45133410/e25cd6ef-b303-4810-9ac5-d364417a027d)

**Comment by JulesLiu** [comment]
> Maybe your graphics memory is too small. 6G or more is OK

3070ti 8G laptop gpu, still got multiple errors. Will try modify virtual memory later, which affects some other projects

**Comment by emrecpp** [comment]
same issue

**Comment by lijingbo666** [comment]
Me too, my graphics card is 3050ti12gb memory

**Comment by cwjcw** [comment]
Thanks all!

**Comment by lijingbo666** [comment]
> 谢谢大家！

解决了吗？

**Comment by Ant1c** [comment]
> Thanks all!

Did you manage to resolve the issue? I'm having the same problemn, but unfortunately can't seem to get around it. The program immediately eats all VRAM and errors.

**Comment by lijingbo666** [comment]
没有解决，我也找不到问题所在，如果你有什么好的办法请告诉我，我会十分感谢你

**Comment by JYF98** [comment]
Same issue randomly occurs.
