### ISSUE TITLE
when i make 2 points and click “drag” btn， some error comes in termital：  The size of tensor  error

### ISSUE THREAD

**Issue by pea-jj** [Zeqiang-Lai/DragGAN#45]
RuntimeError: The size of tensor a (1024) must match the size of tensor b (300) at non-singleton dimension 3

**Comment by AndPuQing** [comment]
same

**Comment by Zeqiang-Lai** [comment]
which model do you use ? do you use custom image ?

**Comment by AndPuQing** [comment]
I believe the issue may have been caused by a failure to load the mask image, resulting in only a partial image being loaded. However, after restarting the server, the problem was resolved.

**Comment by pea-jj** [comment]
> 
first default model    and  default image

**Comment by pea-jj** [comment]
> I believe the issue may have been caused by a failure to load the mask image, resulting in only a partial image being loaded. However, after restarting the server, the problem was resolved.

Thank you. The default mask config has some issues. Refreshing it can resolve the problem.
