### ISSUE TITLE
colab deploy error

### ISSUE THREAD

**Issue by forczc** [Zeqiang-Lai/DragGAN#5]
![企业微信截图_16846671269829](https://github.com/Zeqiang-Lai/DragGAN/assets/13718643/42862d15-6bb4-464e-8f87-9a3133c32aee)
![image](https://github.com/Zeqiang-Lai/DragGAN/assets/13718643/d257b134-95e1-4f32-aad5-fce828d7eb76)

**Comment by Zeqiang-Lai** [comment]
Did you enable the GPU at “代码执行程序/更改运行时类型“ ？

**Comment by forczc** [comment]
> Did you enable the GPU at “代码执行程序/更改运行时类型“ ？

可以了，调为GPU就可以了，感谢～
