### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by seasnakes** [Zeqiang-Lai/DragGAN#50]
When I tried to deploy the web UI code of Gradio locally and clicked on the setup handle point, an error occurred: 'Expecting value: line 1 column 1 (char 0).

**Comment by yuepengyu11** [comment]
same problem

**Comment by Pactortester** [comment]
+1

`Expecting value: line 1 column 1 (char 0)
`

**Comment by Zeqiang-Lai** [comment]
I cannot reproduce this issue. Is it possible to record the screen to help me to identify the problem ?

**Comment by wangxiaochun520** [comment]
set demo.queue().lauch(enable_queue=False)
eg:
demo.queue(concurrency_count=1, max_size=20).launch(share=args.share, server_name=args.ip, server_port=args.port, enable_queue=False)
it work!

**Comment by wangxiaochun520** [comment]
some problem,
while set enable_queue=False,the "Expecting value: line 1 column 1 (char 0)" not occurred,
but press diag it ,the "ValueError: Need to enable queue to use generators" error occurred
 demo.queue(concurrency_count=1, max_size=20).launch(share=args.share, server_name=args.ip, server_port=args.port,enable_queue=False)
while set enable_queue=True,the "Expecting value: line 1 column 1 (char 0)"error occurred
guess should be Gradio's problem

**Comment by wangxiaochun520** [comment]
new find:while run DragGAN/colab.ipynb,it work ,no error occurred,
just set:demo.queue(concurrency_count=1, max_size=20).launch(share=True)

**Comment by YanTianlong-01** [comment]
确实，一样的问题。+1

**Comment by Zeqiang-Lai** [comment]
It seems like it is caused by out-of-memory error. Could you check if your GPU memory is larger than at least 6 GB ?

**Comment by ywdong** [comment]
> It seems like it is caused by out-of-memory error. Could you check if your GPU memory is larger than at least 6 GB ?看起来它是由内存不足错误引起的。你能检查一下你的 GPU 内存是否大于至少 6 GB 吗？

GPU内存有30G, 是够的，但是还是会有一样的问题，打开gradio之后，只要一操作就会有这个问题。

**Comment by ywdong** [comment]
> some problem, while set enable_queue=False,the "Expecting value: line 1 column 1 (char 0)" not occurred, but press diag it ,the "ValueError: Need to enable queue to use generators" error occurred demo.queue(concurrency_count=1, max_size=20).launch(share=args.share, server_name=args.ip, server_port=args.port,enable_queue=False) while set enable_queue=True,the "Expecting value: line 1 column 1 (char 0)"error occurred guess should be Gradio's problem

Same error!!

**Comment by Zeqiang-Lai** [comment]
我无法复现大家的问题，所以没有办法解决。如果大家方便的话，可以录一个屏展示一下复现过程。

I am unable to reproduce everyone's problem, so there is no way to solve it. If it's convenient for everyone, you can record a screen to show the reproduction process.

**Comment by ruxin123** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9150
this is work for me
关掉代理即可

**Comment by Pactortester** [comment]
> AUTOMATIC1111/stable-diffusion-webui#9150

原来是 magic 的问题 ，糟透了

**Comment by seasnakes** [comment]
代理的问题  因为是在wsl里bashrc中写的代理相关的环境变量 虽然宿主机代理关了，但bashrc中相应代理环境变量忘记注释掉了，所以会有该问题，不过根据之前stable-diffusion-webui 中的经验 gradio中添加--no-gradio-queue 类似的命令行参数也许能解决gradio和代理冲突的问题

**Comment by hnuzhoulin** [comment]
愁，关掉魔法就需要提前下载好model

**Comment by syk-3** [comment]
> [AUTOMATIC1111/stable-diffusion-webui#9150](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9150) 这对我有用 关掉代理即可

关闭代理但显示无法连接，请问您是如何解决的？
