### ISSUE TITLE
'--port' default type should be int

### ISSUE THREAD

**Issue by XiaoluDing** [Zeqiang-Lai/DragGAN#58]
when I run the command :
`python -m draggan.web --port=9527 --ip 1xx.xx.xxx.xx`

the error log told me:

  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1703, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/usr/local/lib/python3.9/dist-packages/gradio/networking.py", line 118, in start_server
    s.bind((LOCALHOST_NAME, server_port))
TypeError: an integer is required (got type str)

Maybe the '**--port**' default type should be int

**Comment by Zeqiang-Lai** [comment]
You are right. Fixed with d73c912b5c9728a604824b19a9df55a22b5441da
