### ISSUE TITLE
使用自己训练的stylegan2ada模型时报错

### ISSUE THREAD

**Issue by PetentWong** [Zeqiang-Lai/DragGAN#60]
您好，当我使用如下代码测试自己训练stylegan2-ada-pytorch的模型时遇到报错,
<img width="1187" alt="image" src="https://github.com/Zeqiang-Lai/DragGAN/assets/109642333/7f98ab16-0d94-42ff-b53f-40fa4e50b706">
此处主要修改了
1. load模型的方式由torch.load变为pickle.load, 主要因为模型训练出来是pkl格式的,torch.load也会报错，下图是torch.load的报错
<img width="1157" alt="image" src="https://github.com/Zeqiang-Lai/DragGAN/assets/109642333/b3eb03dd-4930-4ead-b33d-70e7c265b579">
2. 添加了stylegan2-ada-pytorch的git路径到环境，否则会报没有torch_utils的错
3. 同时注意到pickle加载模型后没有g_ema.改为了G_ema
但使用pickle.load后可以加载模型，但在load_state_dict处会报错
<img width="1163" alt="image" src="https://github.com/Zeqiang-Lai/DragGAN/assets/109642333/1820cfce-2947-40fc-9a94-5454f103570f">
Hope for your reply! Thanks

**Comment by Zeqiang-Lai** [comment]
对于pickle格式的ckpt需要用这个脚本转换一下

https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/export_weights.py

**Comment by PetentWong** [comment]
> 对于pickle格式的ckpt需要用这个脚本转换一下
> 
> https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/export_weights.py

感谢，此方法有用
