### ISSUE TITLE
ImportError: /root/.cache/torch_extensions/py310_cu117/fused/fused.so

### ISSUE THREAD

**Issue by codearm2** [Zeqiang-Lai/DragGAN#9]
WARNING: Ignoring invalid distribution -orch (/usr/local/lib/python3.10/dist-packages)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-4-dc352d424c7a>](https://localhost:8080/#) in <cell line: 10>()
      8 get_ipython().system('pip install -r DragGAN/requirements.txt')
      9 
---> 10 from gradio_app import main

7 frames
[/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py](https://localhost:8080/#) in _import_module_from_library(module_name, path, is_python_module)
   1934         spec = importlib.util.spec_from_file_location(module_name, filepath)
   1935         assert spec is not None
-> 1936         module = importlib.util.module_from_spec(spec)
   1937         assert isinstance(spec.loader, importlib.abc.Loader)
   1938         spec.loader.exec_module(module)

ImportError: /root/.cache/torch_extensions/py310_cu117/fused/fused.so: cannot open shared object file: No such file or directory

I tried different pytorch version with no success

**Comment by Zeqiang-Lai** [comment]
You might need a GPU to run it.

**Comment by codearm2** [comment]
> You might need a GPU to run it.
> 
> For colab demo, here you could switch the env to use T4 GPU
> 
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/26198430/239746352-024524b9-0c19-4647-9977-c5deafad7820.png">

My bad, I forgot that I use my remote pc without gpu :(
