### ISSUE TITLE
[Bug] afhqcat.pkl cannot be downloaded!

### ISSUE THREAD

**Issue by FunnySaltyFish** [Zeqiang-Lai/DragGAN#92]
When trying to run `web,py` ,it will try to dowload as follows:

```
ada/afhqcat.pkl not found
Try to download from huggingface:  https://huggingface.co/aaronb/StyleGAN2/resolve/main/ada/afhqcat.pkl
afhqcat.pkl: 0.00B [00:00, ?B/s]
```

When opening the url <https://huggingface.co/aaronb/StyleGAN2/tree/main/ada>, we can see there are no `pkl` files!

> By the way, the `ipynb` file is old and cannot run successfully.

**Comment by Zeqiang-Lai** [comment]
The download url is fixed at version 1.1.5. Colab should work now as well.

**Comment by FunnySaltyFish** [comment]
So fast! I saw your changes, and I'm wondering why you choose to copy the content of `web.py` instead of modifying the `ipynb`? You MUST MODIFY TWICE IF YOU MODIFT ONE OF THEM latter. In my opinion, it's better to change the `ipynb` like:

```bash
!cd DragGAN && python -m draggan.web # since you use relative import, so we should use -m to tell what the model is.
```

**Comment by FunnySaltyFish** [comment]
By the way, the official version of DragGAN was released just now:`https://github.com/XingangPan/DragGAN`
